# https://www.dropwizard.io/en/latest/manual/jdbi3.html
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: geolocation
  password: putmeingitsecrets
  url: jdbc:mysql://localhost:3306/geolocations?serverTimezone=UTC
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

# https://www.dropwizard.io/en/latest/manual/configuration.html#logging
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"
